### ISSUE TITLE
AIABMX 3.4 settings back to default when did something

### ISSUE THREAD

**Issue by xiaoxufeiji1a** [ManlyMarco/KKABMX#13]
I'm using AIABMX 3.4 for AI syoujyo Ver. 1.0.1 (I guess that is game version)

All bone settings back to default (100) when I did something like:
**1.** Loaded Costume Card inside ,it will restore all bone settings to default 100
**2.** Inside main game(story).Start story with a set girl, then go to "Data Terminal" replace set girl with other girl,save game.Restart game and replace set girl back.She's bone settings will go wrong.

so now,I cannot using Character Creation to change girl's costume.
And have problem with switching female character during story play.

**Comment by ManlyMarco** [comment]
Thank you for the report! Can you check if this build fixes the issue? [AIAPI.zip](https://github.com/ManlyMarco/KKABMX/files/3782588/AIAPI.zip)

**Comment by ManlyMarco** [comment]
It sounds like you need to update your BepisPlugins to latest version. https://github.com/IllusionMods/BepisPlugins/releases

I believe that I fixed your original issue, this should load coordinate cards correctly now 
[aiabmx test.zip](https://github.com/ManlyMarco/KKABMX/files/3785273/aiabmx.test.zip)

**Comment by xiaoxufeiji1a** [comment]
> It sounds like you need to update your BepisPlugins to latest version. https://github.com/IllusionMods/BepisPlugins/releases
> 
> I believe that I fixed your original issue, this should load coordinate cards correctly now
> [aiabmx test.zip](https://github.com/ManlyMarco/KKABMX/files/3785273/aiabmx.test.zip)

I am latest version of that.
So I guess my game file somewhere broken.
Thanks for support! I gonna try it clean install and test aiabmx.test.zip

**Comment by xiaoxufeiji1a** [comment]
I tested 3 different times:

1st:
AIAPI.zip(https://github.com/ManlyMarco/KKABMX/files/3782588/AIAPI.zip)
+ release AIABMX v3.4
Result: Doesn't work,seems it doesn't save bone settings to file.

2nd:
aiabmx test.zip(https://github.com/ManlyMarco/KKABMX/files/3785273/aiabmx.test.zip)
+ release AIAPI.v1.8.zip
Result: It can save bone settings to file.And load coordinate cards correctly now.
But bug still: **2.**when you select other girl and save story game.And restart game -- load the save -- select the girl who has bone settings.Girl appear,and bone settings lost.

3rd:
AIAPI.zip(https://github.com/ManlyMarco/KKABMX/files/3782588/AIAPI.zip)
+ aiabmx test.zip(https://github.com/ManlyMarco/KKABMX/files/3785273/aiabmx.test.zip)
Result: Doesn't work,seems it doesn't save bone settings to file.

That's it,I guess it still have story game bug.
Thanks for support!

**Comment by ManlyMarco** [comment]
I see, thank you for testing it. I didn't get this far into the game yet. When I get to that point I'll be able to see what is wrong.

**Comment by xiaoxufeiji1a** [comment]
> Fixed in upcoming release.

I tested AIAPI 1.9 + AIABMX 3.5 + BepInEx_x64_afea187_5.0.0.165(and BepInEx5_Almost-RC2_x64) + AIGirl_BepisPlugins_r12.3.1.
I guess that replace girl bug still there.
what's wrong with it?I guess my game was clean?

**Comment by ManlyMarco** [comment]
Do you have the latest game patch?

**Comment by xiaoxufeiji1a** [comment]
> Do you have the latest game patch?

well.I haven't saw new update,I thought mine was latest.
sorry for bothering.maybe I should seek some new

**Comment by ManlyMarco** [comment]
There was a new version of AIAPI released that might have fixed your issues, if they weren't already resolved.

**Comment by DarkseidOMEGAeffect42** [comment]
I have the same issue as xiaoxufeiji1a. Maybe a registry problem?

**Comment by ManlyMarco** [comment]
Finally, good to hear that.

**Comment by DarkseidOMEGAeffect42** [comment]
I did get a bug with DHH madworld after doing so though. Not sure if it has to do with it.
